---
title: "GroupProject2"
author: "Camden Bartelt Cody Smith Isaias Sanchesz Saavedra"
date: "2023-05-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Objective 1

```{r Objective 1}
library(here)
library(dplyr)
library(tidyr)
library(data.table)
library(leaflet)

filePath <- paste(here(), "Covid_Data", sep = "/")

Global_Confirmed <- as.data.table(read.csv(paste(filePath, "Global_Confirmed.csv", sep = "/")))
Global_Deaths <- as.data.table(read.csv(paste(filePath, "Global_Deaths.csv", sep = "/")))

#Collapsing data set so each country only has 1 entry for use throughout the project

Global_Deaths_Collapsed <- Global_Deaths %>%
  group_by(Global_Deaths[[2]]) %>%
  summarize(across(5:ncol(Global_Deaths), sum)) %>%
  rename(Country = "Global_Deaths[[2]]")

Global_Confirmed_Collapsed <- Global_Confirmed %>%
  group_by(Global_Confirmed[[2]]) %>%
  summarize(across(5:ncol(Global_Confirmed), sum)) %>%
  rename(Country = "Global_Confirmed[[2]]")

#Creating the mean for the Lattitude/Longitude and adding it to the column. Access via name, the positions are at the back of the data table.
# Names are Lat and Long

globalLatLong <- Global_Confirmed %>%
  group_by(Global_Confirmed[[2]]) %>%
  # Originally was summarize(across(3:4, mean, na.rm = TRUE)), Rstudio suggested this due to the method being depreceated 
  summarize(across(3:4,\(x) mean(x, na.rm = TRUE)))

globalLatLong <- globalLatLong[, 2:3]

#Creating data table for use in leaflet, has most recent data, as well as the lattitude and longitutde of the countries
Global_Recent_Data = mutate(Global_Confirmed_Collapsed[,c(1, ncol(Global_Confirmed_Collapsed))])
colnames(Global_Recent_Data)[2] <- "Confirmed"

Global_Recent_Data = mutate(Global_Recent_Data, Global_Deaths_Collapsed[,c(ncol((Global_Deaths_Collapsed)))], globalLatLong)
colnames(Global_Recent_Data)[3] <- "Deaths"

#Defining color quantiles for the leaflet map
colorDeaths <- colorQuantile(c("darkblue","darkgray", "red"), Global_Recent_Data$Deaths, n = 9)

colorConfirmed <- colorQuantile(c("darkblue","darkgray", "red"), Global_Recent_Data$Confirmed, n = 9)

#Create Leaflet Map
leaflet(data = Global_Recent_Data) %>% addTiles %>%
  addCircleMarkers(
    #Creating markers for confirmed
    lng = ~Long, 
    lat = ~Lat, 
    popup = ~paste("Confirmed: ", format(Confirmed, big.mark = ",")), 
    label = ~as.character(Country),
    color = ~colorConfirmed(Confirmed),
    group = "Confirmations",
    fillOpacity = 0.7,
    radius = 3
  ) %>%
  addCircleMarkers(
    #Creating markers for deaths
    lng = ~Long, 
    lat = ~Lat, 
    popup = ~paste("Deaths: ", format(Deaths, big.mark = ",")), 
    label = ~as.character(Country),
    color = ~colorDeaths(Deaths),
    group = "Deaths",
    fillOpacity = 0.7,
    radius = 3
  ) %>%
  addLayersControl(
    #Chose base groups instead of layered so that you would only have one visible at a time
    baseGroups = c("Confirmations", "Deaths"),
    options = layersControlOptions(collapsed = FALSE)
  )

```

# Objective 2

```{r Objective 2}
library(kableExtra)
library(tibble)
#Getting data and sorting it into descending order, keeping names of the countries consistent with data
DataSet <- mutate(
  Global_Confirmed_Collapsed[,c(1, ncol(Global_Confirmed_Collapsed))] %>% 
    arrange(desc(.[,2])) %>%
    #Space in the name differntiates the two data columns for countries
    rename(Confirmed = 2, "Country " = 1), 
  
  Global_Deaths_Collapsed[,c(1, ncol(Global_Deaths_Collapsed))] %>% 
    arrange(desc(.[,2])) %>%
    rename(Deaths = 2, "Country" = 1))

#Adding rank column and putting it at the front

DataSet <- DataSet %>%
  mutate("Rank" = row_number()) %>%
  select(Rank, everything())

kbl(DataSet) %>%
  #Keeping header at top even after scrolling down
  kable_styling(fixed_thead = TRUE) %>%
  add_header_above(c(" " = 1, "Confirmations" = 2, "Deaths" = 2)) %>%
  scroll_box(width = "800px", height = "400px")



```

# Objective 3

```{r Objective 3}
library(stringr)
library(ggplot2)
library(scales)
library(cowplot)
#Load sorted data for california locations and sort in descending order
US_Confirmations = as.data.table(read.csv(paste(filePath, "US_Confirmed.csv", sep = "/")))[, -c(1:5, 8, 11)]
California_Confirmations <- US_Confirmations %>%
  filter(Province_State == "California") %>%
  arrange(desc(across(ncol(.))))

#Summarize all of california data, and then fix dates
California_Total_Confirmations <- California_Confirmations %>%
  summarize(across(5:ncol(California_Confirmations), sum)) %>%
  gather(key = "Date", value = "Confirmations")
California_Total_Confirmations$Date <-str_replace_all(California_Total_Confirmations$Date, c("X" = "", "\\." = "/"))
California_Total_Confirmations$Date <- as.Date(California_Total_Confirmations$Date, format = "%m/%d/%Y")

#Get top 3 cities, convert to long, and fix the date column to actually be dates
California_Top3 <- California_Confirmations[,-c(2:4)] %>%
  head(3) %>%
  pivot_longer(cols = -"Admin2", names_to = "Date", values_to = "Confirmations")
California_Top3$Date <-str_replace_all(California_Top3$Date, c("X" = "", "\\." = "/"))
California_Top3$Date <- as.Date(California_Top3$Date, format = "%m/%d/%Y")

plotTotal <- ggplot(California_Total_Confirmations, aes(x = Date, y = Confirmations)) +
                #Creating plot and vertical lines with text labels
                geom_line(linewidth = 2) +
                geom_vline(xintercept = as.Date(c("0020-03-19", "0021-01-29", "0021-07-4", "0021-12-20")), 
                           linetype = "dashed", color = c("blue", "blue", "red", "red"),
                           linewidth = 1) +
                #Errors were being thrown so I decided to create a new data frame for the labels and pass that in, and it worked. 
                geom_text(data = data.frame(x = as.Date(c("0020-03-19", "0021-01-29", "0021-07-4", "0021-12-20")),
                                           y = 7500000, label = c("SAH", "EUA\n +6 Weeks", "Delta", "Omicron")),
                          aes(x = x, y = y, label = label),
                          vjust = -0.5,
                          hjust = 1.1,
                          size = 3) +
                labs(x = "Date", y = "Cases", title = "COVID-19 confirmations in California") +
                #Shrinking down text so it doesnt overlap
                scale_x_date(breaks = as.Date(c("0020-03-19", "0021-01-29", "0021-07-4", "0021-12-20")),
                  labels = c("0020-03-19", "0021-01-29", "0021-07-4", "0021-12-20") ) +
                #Commas for y axis
                scale_y_continuous(labels = scales::comma_format()) +
                #Compressing the graphs width a bit to make the two graphs nearly the same size
                theme(plot.margin = margin(0, 100, 0, 0), axis.text.x = element_text(size = 8))
plotTop3 <- ggplot(California_Top3, aes(x = Date, y = Confirmations, color = Admin2)) +
                geom_line(linewidth = 1.5) +
                geom_vline(xintercept = as.Date(c("0020-03-19", "0021-01-29", "0021-07-4", "0021-12-20")), 
                           linetype = "dashed", color = c("blue", "blue", "red", "red"),
                           linewidth = 1) +
                scale_color_manual(values = setNames(c("darkblue", "darkviolet", "blue"), unique(California_Top3$Admin2))) + 
                labs(x = "Date", y = "Cases", color = "") +
                scale_y_continuous(labels = scales::comma_format(width = 8))

#Create plot grid with the 2 graphs on top of eachother
plot_grid(
  plotTotal,
  plotTop3,
  align = "Center",
  ncol = 1
)

```

# Objective 4

```{r Objective 4}
US_Deaths = as.data.table(read.csv(paste(filePath, "US_Deaths.csv", sep = "/")))

ConfirmPop = mutate(US_Deaths[,12:12], US_Confirmations[,ncol(US_Confirmations):ncol(US_Confirmations)]) %>%
  rename(Population = 1, Cases = 2)

DeathConfirm = US_Deaths[,ncol(US_Deaths):ncol(US_Deaths)] %>%
  #Since both CSVs last data point will be the same date, the data would be overwritten, so I renamed and then mutated in the data set for confirmations
  rename(Deaths = 1) %>%
  mutate(.,US_Confirmations[,ncol(US_Confirmations):ncol(US_Confirmations)]) %>%
  rename(Cases = 2)

#Creating first plot with a logmarithic scaling
plot1 <- ggplot(ConfirmPop, aes(x = Population, y = Cases)) +
                  geom_point(color = "blue") +
                  labs(x = "Population", y = "Confirmation Counts", title = "Confirmations Vs. Population") +
                  scale_x_log10(labels = scales::comma_format(width = 8)) + scale_y_log10(labels = scales::comma_format(width = 8))
#Creating second plot with a logmarithic scaling
plot2 <- ggplot(DeathConfirm, aes(x = Cases, y = Deaths)) +
                  geom_point(color = "red") +
                  labs(x = "Confirmation Counts", y = "Death Counts", title = "Deaths Vs. Confirmations") + 
                  scale_x_log10(labels = scales::comma_format(width = 8)) + scale_y_log10(labels = scales::comma_format(width = 8))
                  
#Creating output with the graphs side by side
plot_grid(
  plot1, 
  plot2
)
```